### ISSUE TITLE
Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.

### ISSUE THREAD

**Issue by libill** [Kotlin/kmm-production-sample#12]
gradlew packForXcode --debug --info

* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

can I use Java 1.8?

**Comment by terrakok** [comment]
This sample uses Jetpack Compose which uses latest Android Gradle Plugin which uses gradle 7.0 which requires java 11

**Comment by libill** [comment]
> This sample uses Jetpack Compose which uses latest Android Gradle Plugin which uses gradle 7.0 which requires java 11

thank you!
