### ISSUE TITLE
Cannot add new feed

### ISSUE THREAD

**Issue by nwagu** [Kotlin/kmm-production-sample#26]
When I enter a feed url (https://xkcd.com/atom.xml) and click add, I get a toast saying :

`expected: START_TAG {null}channel (position:START_TAG <title>@2:64 in java.io.StringReader@a71eb8a)`

The error logs I can see when I run it in debug mode include:

`D/FeedStore: Action: Error(error=org.xmlpull.v1.XmlPullParserException: expected: START_TAG {null}channel (position:START_TAG <title>@2:64 in java.io.StringReader@a71eb8a) )`

**Comment by terrakok** [comment]
This is rss reader. Not atom.
You have to use rss feed link:

**Comment by nwagu** [comment]
Okay, I will close this since I can see another issue to support atom feeds. Thanks for the clarification.
