### ISSUE TITLE
Error: Building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64 (M1)

### ISSUE THREAD

**Issue by avjiang** [Kotlin/kmm-production-sample#27]
Hi, really appreciate if anyone can help me in building to M1 simulator

https://github.com/Kotlin/kmm-sample/issues/60

**Comment by terrakok** [comment]
Hi! M1 support is in development at the moment. It will available with Kotlin 1.5.30
But you can work with project via rosetta

**Comment by avjiang** [comment]
Hi @terrakok thank you so much for the info! I thought I have missed out something. Thanks!

**Comment by lerik1** [comment]
Good day! When is Kotlin 1.5.30 released, or where you can download it?

> Hi! M1 support is in development at the moment. It will available with Kotlin 1.5.30
> But you can work with project via rosetta

Good day! When is Kotlin 1.5.30 released, or where you can download it?
