### ISSUE TITLE
Project doesn't build

### ISSUE THREAD

**Issue by slipdef** [Kotlin/kmm-production-sample#29]
Unrecognized Android Studio (or Android Support plugin for IntelliJ IDEA) version '202.7660.26.42.7486908', please retry with version 2020.3.1 or newer

**Comment by KaterinaPetrova** [comment]
Hey @slipdef! Please check if it works with the latest version of the project and Android Studio Arctic Fox.

**Comment by slipdef** [comment]
It works indeed.
