### ISSUE TITLE
Why SwiftUI and Compose

### ISSUE THREAD

**Issue by slipdef** [Kotlin/kmm-production-sample#30]
It contradicts with the project goal - "It's been designed to demonstrate how KMM can be used in real production projects.​​"
These 2 UI frameworks are not production ready and only few people would risk to use it in prod (SwiftUI especially). I came here to see real KMM production use and ended up with SwiftUI/Compose and the need to install Android Studio Preview version. Doesn't make any sense for the prodection app.

**Comment by KaterinaPetrova** [comment]
Hey @slipdef ! Thanks for the question. The UI part is this sample is not the main point — you can easily connect any UI implementation on both platforms without any changes in the shared module. And that's the beauty of KMM — it doesn't impose any resctrions on how you develop your app's UI. BTW initially the Android part was written without Compose, [check this migration commit](https://github.com/Kotlin/kmm-production-sample/commit/e2ee0ed0e2154b9e57184bc639a9cd47551e6428).
The most popular question developers are thinking about when they start using KMM — how to organize their code with KMM, what architecture to use, which parts of code to share. And exactly this we tried to demonstrate in our sample. We used one (but not the only one!) of the possible approaches, where we share data and domain layers of the app, and also the application state using simplified redux architecture implementation.

**Comment by slipdef** [comment]
Thanks for the answer. Just not been able to run it on the usual prod environment surprised me.
