### ISSUE TITLE
Run androidApp, show error:This version (1.0.0-beta07) of the Compose Compiler requires Kotlin version 1.4.32

### ISSUE THREAD

**Issue by libill** [Kotlin/kmm-production-sample#31]
e: This version (1.0.0-beta07) of the Compose Compiler requires Kotlin version 1.4.32 but you appear to be using Kotlin version 1.5.21 which is not known to be compatible.  Please fix your configuration (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':androidApp:compileDebugKotlin'.

**Comment by terrakok** [comment]
Fixed.
