### ISSUE TITLE
Can't  Build the ios app after a clean clone of the project

### ISSUE THREAD

**Issue by RofaeilAshaiaa** [Kotlin/kmm-production-sample#35]
After I cloned and opened the project  in Android Studio, I managed to run the android app but I can't run the ios app neither from android studio nor from xcode (I'm an android developer and I don't have experience with ios).

When I try to run the ios app from android studio I get the following error
Error: can't grab Xcode schemes with /usr/bin/xcodebuild -project /Volumes/data/Projects/Kotlin/KotlinMultiPlatform/kmm-production-sample/iosApp/iosApp.xcodeproj -list

<img width="1280" alt="Screen Shot 2021-07-31 at 6 48 44 PM" src="https://user-images.githubusercontent.com/21986326/127746791-c91f8456-5c4e-445b-9566-74c9c60e30f5.png">

And when I try to build the ios app from xcode I get the following error
<img width="1392" alt="Screen Shot 2021-07-31 at 6 36 56 PM" src="https://user-images.githubusercontent.com/21986326/127746488-92ed27bb-b53d-4150-8e03-fb2a6ed43193.png">

Environment:
Device: Macbook Pro 2020 with apple M1
OS: macOS Big Sur 11.5
IDE: Android Studio Arctic Fox 2020.3.1 and Xcode Version 12.5.1

**Comment by terrakok** [comment]
https://github.com/Kotlin/kmm-production-sample/issues/27

**Comment by RofaeilAshaiaa** [comment]
Thank you @terrakok for your reply.

I already faced the problem mentioned in the issue #27 when I tried to build the [kmm-sample](https://github.com/Kotlin/kmm-sample)  and managed to solve the mentioned problem in both the kmm-sample and kmm-production-sample.
 
 What I'm facing here is another problem that I faced after I updated the android studio to Android Studio Arctic Fox 2020.3.1 and Xcode to Xcode Version 12.5.1.

**Comment by KaterinaPetrova** [comment]
Hey @RofaeilAshaiaa! The problem was in the wrong Introspect location in SPM, this fix should solve your issue https://github.com/Kotlin/kmm-production-sample/commit/88caf9a59dc39b9fe4aaf275f51f99a406a3533e, please check the updated project

**Comment by RofaeilAshaiaa** [comment]
Thank you @KaterinaPetrova for the fix!

I can now confirm that the project can build and run from both Xcode and from Android Studio
