### ISSUE TITLE
my project can not   create   the share.Framework  normally  

### ISSUE THREAD

**Issue by WngYilei** [Kotlin/kmm-production-sample#57]
Kotlin 1.8
xcode  14.2
Android studio Android Studio Electric Eel | 2022.1.1 Patch 1
Compose 1.3.0  

when i  add the  plgin    id("org.jetbrains.compose")  in share moudle 's build.gradle.kts , run  podspec task, can not create the share.Framework , in the  build/cocoapods/framework/shared.framework/Headers  is not share.h  , but  placeholder.h  ,and it is empty 。  

i  want get  some help  ,thinks

**Comment by terrakok** [comment]
Please, create an issue on YouTrack: https://youtrack.jetbrains.com/issues/KT
It's not a question about the RSS reader
