### ISSUE TITLE
Cant run on Xcode

### ISSUE THREAD

**Issue by anthonyfebrian** [Kotlin/kmm-production-sample#75]
Hi, i got some error on xcode but run perfectly on android studio. 

<img width="804" alt="Screenshot 2023-10-04 at 11 18 53" src="https://github.com/Kotlin/kmm-production-sample/assets/5362461/75c33a54-5cc6-426d-b5f7-d0b835ffb44f">

**Comment by pahill** [comment]
Thanks for reporting this! Will look into it soon, or delegate! 

Have a great day :)

**Comment by pahill** [comment]
It should be fixed now.
